# Generated by Django 3.1.5 on 2023-01-06 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFooiyti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fooiyti_e', models.FloatField(blank=True, default=50, null=True)),
                ('fooiyti_i', models.FloatField(blank=True, default=50, null=True)),
                ('fooiyti_n', models.FloatField(blank=True, default=50, null=True)),
                ('fooiyti_s', models.FloatField(blank=True, default=50, null=True)),
                ('fooiyti_t', models.FloatField(blank=True, default=50, null=True)),
                ('fooiyti_f', models.FloatField(blank=True, default=50, null=True)),
                ('fooiyti_c', models.FloatField(blank=True, default=50, null=True)),
                ('fooiyti_a', models.FloatField(blank=True, default=50, null=True)),
                ('feed', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='feeds.feed')),
            ],
        ),
    ]
