# Generated by Django 3.1.5 on 2023-01-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20230106_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='pioneer',
            name='fooiyti_a',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='pioneer',
            name='fooiyti_c',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='pioneer',
            name='fooiyti_e',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='pioneer',
            name='fooiyti_f',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='pioneer',
            name='fooiyti_i',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='pioneer',
            name='fooiyti_n',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='pioneer',
            name='fooiyti_s',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='pioneer',
            name='fooiyti_t',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
    ]
