# Generated by Django 3.1.5 on 2023-01-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20230110_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedfooiyti',
            name='fooiyti_a',
            field=models.SmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedfooiyti',
            name='fooiyti_c',
            field=models.SmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedfooiyti',
            name='fooiyti_e',
            field=models.SmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedfooiyti',
            name='fooiyti_f',
            field=models.SmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedfooiyti',
            name='fooiyti_i',
            field=models.SmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedfooiyti',
            name='fooiyti_n',
            field=models.SmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedfooiyti',
            name='fooiyti_s',
            field=models.SmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedfooiyti',
            name='fooiyti_t',
            field=models.SmallIntegerField(blank=True, default=50, null=True),
        ),
    ]
