# Generated by Django 3.1.5 on 2023-01-31 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0006_auto_20230116_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='피드 댓글 pk')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='댓글 내용')),
                ('order', models.PositiveIntegerField(blank=True, default=1000, null=True, verbose_name='댓글 순서')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='댓글 작성일')),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_comment', to='feeds.feed')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_comment', to='feeds.feedcomment', verbose_name='상위 댓글 정보')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
