# Generated by Django 3.1.5 on 2023-02-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_auto_20230131_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedcomment',
            options={'verbose_name': '4.3.1 피드 댓글', 'verbose_name_plural': '4.3.1 피드 댓글'},
        ),
        migrations.AlterModelOptions(
            name='feedfooiyti',
            options={'verbose_name': '4.3.1 피드 푸이티아이', 'verbose_name_plural': '4.3.1 피드 푸이티아이'},
        ),
        migrations.AddField(
            model_name='feedcomment',
            name='is_reported',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='신고된 댓글'),
        ),
    ]
