# Generated by Django 3.1.5 on 2023-02-05 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_feedparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedparty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일'),
            preserve_default=False,
        ),
    ]
