warning = {
    4000: "does not exist required field",
    4001: "can not use name",
    4002: "does not exist required fields",
    4003: "does not exist required fields (is_confirm)",
    4016: "does not able to use that nickname",
    4017: "already pioneered",
    4018: "does not exist required field",
    4019: "does not exist required field",
    4020: "does not exist address field",
    4021: "does not exist required field",
    4028: "does not exist correspond pioneer id",
    4033: "does not exist required field",
    4035: "does not exist correspond pioneer id",
    4036: "does not exist required field",
    4037: "does not correct type",
    4038: "does not exist required field",
    4042: "does not exist required field in path",
    4045: "does not exist required field",
    4046: "does not exist required field",
    4047: "account search failed",
    4048: "does not exist required field",
    4049: "does not exist required field",
    4050: "does not exist required field",
    4303: "Forbidden auth account",
    4404: "not found",
    4987: "dose not exist party_id field",
    4988: "dose not exist party from party_id",
    4989: "dose not exist comment_id field",
    4990: "dose not exist comment from comment_id",
    4991: "required login api",
    4992: "dose not exist feed_id field",
    4993: "dose not exist feed from feed_id",
    4994: "get account from request error",
    4995: "fooiy_web_guard authentication failed",
    4996: "dose not exist shop_id field",
    4997: "dose not exist shop from shop_id",
    4998: "duplicate login",
    4999: "authentication failed",
}

error = {
    5000: "unexpected error occurred",
    5001: "shop marker detail failed",
    5002: "pioneer register feed failed",
    5003: "pioneer shop category register failed",
    5005: "logout failed",
    5006: "withdrawal failed",
    5007: "changing profile failed",
    5008: "get archives image list failed",
    5009: "loading fooiyti questions failed",
    5010: "regist pioneer failed",
    5011: "regist record failed",
    5012: "find nearby shop failed",
    5013: "shop search failed",
    5014: "fooiyti result failed",
    5015: "pioneer success transaction failed",
    5016: "get menu list failed",
    5020: "unexpected error occurred",
    5021: "get pioneer info failed",
    5024: "shop map picker failed",
    5025: "shop map list failed",
    5026: "get filter list failed",
    5027: "get account info failed",
    5028: "unexpected error occurred",
    5029: "get feed list api error occured",
    5030: "check pioneer success failed",
    5031: "check pioneer reject failed",
    5033: "init request failed",
    5034: "get shop info failed",
    5035: "notice request failed",
    5036: "regist suggestion failed",
    5037: "get suggestion UI failed",
    5038: "delete record error occur",
    5041: "kakao signup failed",
    5042: "apple signup failed",
    5044: "withdrawal failed",
    5045: "account search failed",
    5046: "push notification list error",
    5047: "mypage picker api error occur",
    5048: "feed update api error occur",
    5049: "mypage picker detail api error occur",
    5050: "get account ranking failed",
    5051: "register feed storage api error occur",
    5052: "withdraw feed storage api error occur",
    5053: "get feed storage list api error occur",
    5054: "register feed like api error occur",
    5055: "withdraw feed like api error occur",
    5056: "spot search list api error occur",
    5057: "get feed comment list api error occur",
    5058: "create feed comment api error occur",
    5059: "patch feed comment api error occur",
    5060: "destroy feed comment api error occur",
    5061: "latest order feeds list api error occur",
    5062: "distance order shops list api error occur",
    5063: "party list api error occur",
    5064: "party create api error occur",
    5065: "party info api error occur",
    5066: "party join api error occur",
    5067: "party join check api error occur",
    5068: "party member list api error occur",
    5069: "party info update api error occur",
    5070: "party search api error occur",
    5071: "party feed list error occur",
    5072: "report feed api error occur",
    5555: "only server for slack notification",
    5993: "get party from request failed",
    5994: "get comment from request failed",
    5995: "get feed from request failed",
    5996: "push notifications failed",
    5997: "get account from request failed",
    5998: "get shop from request failed",
    5999: "authentication failed",
}
