# Generated by Django 3.1.5 on 2022-12-14 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shops.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='매장 pk')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='매장 공개 pk')),
                ('name', models.CharField(blank=True, help_text='ex) 맵도리탕 수원화서점', max_length=50, null=True, verbose_name='매장명')),
                ('is_exposure', models.BooleanField(blank=True, default=True, verbose_name='매장 노출 여부')),
                ('menu_min_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='메뉴 최소 가격')),
                ('menu_max_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='메뉴 최대 가격')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='매장 주소')),
                ('address_depth1', models.CharField(blank=True, help_text='매장 주소 저장 시 자동으로 채워짐', max_length=15, null=True, verbose_name='매장 행정 구역1(도, 광역시, 자치시)')),
                ('address_depth2', models.CharField(blank=True, help_text='매장 주소 저장 시 자동으로 채워짐', max_length=15, null=True, verbose_name='매장 행정 구역2(시, 구, 군)')),
                ('address_depth3', models.CharField(blank=True, help_text='매장 주소 저장 시 자동으로 채워짐', max_length=15, null=True, verbose_name='매장 행정 구역2(읍, 면, 동)')),
                ('longitude', models.CharField(blank=True, db_index=True, help_text='매장 주소 저장 시 자동으로 채워짐', max_length=50, null=True, verbose_name='경도')),
                ('latitude', models.CharField(blank=True, db_index=True, help_text='매장 주소 저장 시 자동으로 채워짐', max_length=50, null=True, verbose_name='위도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='슬러그')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=shops.models.thumbnail_upload_url, verbose_name='썸네일')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='개척자')),
            ],
            options={
                'verbose_name': '2.1 매장 정보',
                'verbose_name_plural': '2.1 매장 정보',
            },
        ),
        migrations.CreateModel(
            name='ShopBadge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': '2.1.2 매장 정보 (배지)',
                'verbose_name_plural': '2.1.2 매장 정보 (배지)',
            },
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': '2.1.1 매장 정보 (카테고리)',
                'verbose_name_plural': '2.1.1 매장 정보 (카테고리)',
            },
        ),
        migrations.CreateModel(
            name='ShopScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=50, verbose_name='매장 피드 평균 점수')),
                ('feed_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='피드 개수')),
                ('is_yummy', models.BooleanField(default=False, verbose_name='푸이슐랭 여부')),
                ('enta_score', models.PositiveSmallIntegerField(default=50, verbose_name='ENTA 점수')),
                ('entc_score', models.PositiveSmallIntegerField(default=50, verbose_name='ENTC 점수')),
                ('enfa_score', models.PositiveSmallIntegerField(default=50, verbose_name='ENFA 점수')),
                ('enfc_score', models.PositiveSmallIntegerField(default=50, verbose_name='ENFC 점수')),
                ('esta_score', models.PositiveSmallIntegerField(default=50, verbose_name='ESTA 점수')),
                ('estc_score', models.PositiveSmallIntegerField(default=50, verbose_name='ESTC 점수')),
                ('esfa_score', models.PositiveSmallIntegerField(default=50, verbose_name='ESFA 점수')),
                ('esfc_score', models.PositiveSmallIntegerField(default=50, verbose_name='ESFC 점수')),
                ('inta_score', models.PositiveSmallIntegerField(default=50, verbose_name='INTA 점수')),
                ('intc_score', models.PositiveSmallIntegerField(default=50, verbose_name='INTC 점수')),
                ('infa_score', models.PositiveSmallIntegerField(default=50, verbose_name='INFA 점수')),
                ('infc_score', models.PositiveSmallIntegerField(default=50, verbose_name='INFC 점수')),
                ('ista_score', models.PositiveSmallIntegerField(default=50, verbose_name='ISTA 점수')),
                ('istc_score', models.PositiveSmallIntegerField(default=50, verbose_name='ISTC 점수')),
                ('isfa_score', models.PositiveSmallIntegerField(default=50, verbose_name='ISFA 점수')),
                ('isfc_score', models.PositiveSmallIntegerField(default=50, verbose_name='ISFC 점수')),
                ('shop', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'verbose_name': '2.1.3 매장 정보 (점수)',
                'verbose_name_plural': '2.1.3 매장 정보 (점수)',
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='badge',
            field=models.ManyToManyField(blank=True, help_text='여러개 선택 가능', to='shops.ShopBadge', verbose_name='배지'),
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='여러개 선택 가능', to='shops.ShopCategory', verbose_name='카테고리'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='메뉴 pk')),
                ('name', models.CharField(blank=True, help_text='ex) 무뼈 닭발', max_length=50, null=True, verbose_name='이름')),
                ('price', models.PositiveIntegerField(default=0, help_text='ex) 12500', verbose_name='가격')),
                ('is_best', models.BooleanField(blank=True, help_text='매장의 대표메뉴 인지', null=True, verbose_name='대표 메뉴 여부')),
                ('is_popular', models.BooleanField(blank=True, help_text='매장의 인기 메뉴인지', null=True, verbose_name='인기 메뉴 여부')),
                ('category', models.CharField(blank=True, choices=[('MAIN', '메인'), ('SET', '세트'), ('SIDE', '사이드'), ('BEVERAGE', '음료'), ('LIQUOR', '주류')], max_length=10, null=True, verbose_name='카테고리')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='shops.shop', verbose_name='매장')),
            ],
            options={
                'verbose_name': '2.2 매장 메뉴 정보',
                'verbose_name_plural': '2.2 매장 메뉴 정보',
            },
        ),
    ]
