# Generated by Django 3.1.5 on 2023-01-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopscore',
            name='fooiyti_a_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopscore',
            name='fooiyti_c_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopscore',
            name='fooiyti_e_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopscore',
            name='fooiyti_f_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopscore',
            name='fooiyti_feed_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='푸이티아이 평가 개수'),
        ),
        migrations.AddField(
            model_name='shopscore',
            name='fooiyti_i_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopscore',
            name='fooiyti_n_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopscore',
            name='fooiyti_s_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shopscore',
            name='fooiyti_t_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
