# Generated by Django 3.1.5 on 2023-01-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20230106_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopscore',
            name='fooiyti_a_percentage',
            field=models.FloatField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopscore',
            name='fooiyti_c_percentage',
            field=models.FloatField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopscore',
            name='fooiyti_e_percentage',
            field=models.FloatField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopscore',
            name='fooiyti_f_percentage',
            field=models.FloatField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopscore',
            name='fooiyti_i_percentage',
            field=models.FloatField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopscore',
            name='fooiyti_n_percentage',
            field=models.FloatField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopscore',
            name='fooiyti_s_percentage',
            field=models.FloatField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopscore',
            name='fooiyti_t_percentage',
            field=models.FloatField(blank=True, default=50, null=True),
        ),
    ]
