# Generated by Django 3.1.5 on 2023-01-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20230106_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopscore',
            name='fooiyti_a_percentage',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopscore',
            name='fooiyti_c_percentage',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopscore',
            name='fooiyti_e_percentage',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopscore',
            name='fooiyti_f_percentage',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopscore',
            name='fooiyti_i_percentage',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopscore',
            name='fooiyti_n_percentage',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopscore',
            name='fooiyti_s_percentage',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopscore',
            name='fooiyti_t_percentage',
            field=models.PositiveSmallIntegerField(blank=True, default=50, null=True),
        ),
    ]
