# Generated by Django 3.1.5 on 2022-12-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221214_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='state',
            field=models.CharField(blank=True, choices=[('subscribe', '구독'), ('unsubscribe', '구독취소')], default='subscribe', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='state',
            field=models.CharField(blank=True, choices=[('subscribe', '구독'), ('unsubscribe', '구독취소')], default='subscribe', max_length=12, null=True),
        ),
    ]
