# Generated by Django 3.1.5 on 2023-01-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221230_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rank',
            field=models.CharField(blank=True, choices=[('ranker', 'RANKER'), ('platinum', 'PLATINUM'), ('gold', 'GOLD'), ('silver', 'SILVER'), ('bronze', 'BRONZE')], max_length=10, null=True, verbose_name='계정 랭크'),
        ),
    ]
