# Generated by Django 3.1.5 on 2023-02-05 09:59

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='파티 pk')),
                ('account_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='파티원 수')),
                ('feed_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='파티 피드 수')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='파티명')),
                ('introduction', models.CharField(blank=True, max_length=100, null=True, verbose_name='파티 소개글')),
                ('party_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.party_image_upload, verbose_name='파티 프로필 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '1.4 파티 정보',
                'verbose_name_plural': '1.4 파티 정보',
            },
        ),
        migrations.CreateModel(
            name='AccountParty',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='유저 파티 중개 테이블 pk')),
                ('state', models.CharField(blank=True, choices=[('subscribe', '가입 중'), ('confirm', '검수'), ('unsubscribe', '미가입'), ('reject', '반려'), ('expulsion', '추방')], default='confirm', max_length=12, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_party', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_party', to='accounts.party')),
            ],
            options={
                'verbose_name': '1.4.1 유저, 파티 관계 정보',
                'verbose_name_plural': '1.4.1 유저, 파티 관계 정보',
                'unique_together': {('account', 'party')},
            },
        ),
    ]
