# Generated by Django 3.1.5 on 2023-01-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSpot',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='위치 검색 pk')),
                ('type', models.CharField(blank=True, choices=[('landmark', '랜드마크'), ('university', '대학교'), ('subway', '지하철역'), ('district', '행정지역')], max_length=10, null=True, verbose_name='위치 타입')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='위치 명')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='매장 주소')),
                ('longitude', models.CharField(blank=True, db_index=True, help_text='매장 주소 저장 시 자동으로 채워짐', max_length=50, null=True, verbose_name='경도')),
                ('latitude', models.CharField(blank=True, db_index=True, help_text='매장 주소 저장 시 자동으로 채워짐', max_length=50, null=True, verbose_name='위도')),
            ],
            options={
                'verbose_name': '5.1 위치 검색 정보',
                'verbose_name_plural': '5.1 위치 검색 정보',
            },
        ),
    ]
