# Generated by Django 3.1.5 on 2022-12-14 12:01

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='계정 pk')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='계정 공개 pk')),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name='이름')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='성')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='이름')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='바밀번호')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프 권한 여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='계정 활성 여부')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='super 유저 권한 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 권한 여부')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='마지막 로그인 날짜')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='회원 가입 날짜')),
                ('social_type', models.CharField(blank=True, choices=[('kakao', '카카오'), ('apple', '애플')], max_length=10, null=True, verbose_name='소셜 타입')),
                ('social_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='소셜 id')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='전화번호')),
                ('old_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='이전 전화번호')),
                ('state', models.CharField(blank=True, choices=[('normal', '정상'), ('sleep', '휴면'), ('withdrawal', '탈퇴')], max_length=10, null=True, verbose_name='계정 상태')),
                ('sleep_reason', models.CharField(blank=True, choices=[('새 번호 주인이 회원가입을 함', '새 번호 주인이 회원가입을 함'), ('새 번호 주인이 전화번호 변경을 함', '새 번호 주인이 전화번호 변경을 함')], max_length=20, null=True, verbose_name='휴면 이유')),
                ('withdrawal_reason', models.CharField(blank=True, max_length=300, null=True, verbose_name='탈퇴 이유')),
                ('date_sleep', models.DateTimeField(blank=True, null=True, verbose_name='휴면일')),
                ('date_withdrawal', models.DateTimeField(blank=True, null=True, verbose_name='탈퇴일')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='이메일')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='닉네임')),
                ('gender', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1, null=True, verbose_name='성별')),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, help_text='ex) 1998', null=True, verbose_name='출생년도')),
                ('fooiyti_e_percentage', models.FloatField(blank=True, null=True)),
                ('fooiyti_i_percentage', models.FloatField(blank=True, null=True)),
                ('fooiyti_n_percentage', models.FloatField(blank=True, null=True)),
                ('fooiyti_s_percentage', models.FloatField(blank=True, null=True)),
                ('fooiyti_t_percentage', models.FloatField(blank=True, null=True)),
                ('fooiyti_f_percentage', models.FloatField(blank=True, null=True)),
                ('fooiyti_c_percentage', models.FloatField(blank=True, null=True)),
                ('fooiyti_a_percentage', models.FloatField(blank=True, null=True)),
                ('account_token', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='푸이 계정 식별 토큰')),
                ('os', models.CharField(blank=True, max_length=10, null=True, verbose_name='OS')),
                ('device_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='기기 id')),
                ('app_version', models.CharField(blank=True, max_length=10, null=True, verbose_name='앱 버전')),
                ('fcm_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='fcm 토큰')),
                ('is_mkt_agree', models.BooleanField(blank=True, null=True, verbose_name='마케팅 정보 수신 동의 여부')),
                ('date_mkt_agree', models.DateTimeField(blank=True, null=True, verbose_name='마케팅 정보 수신 동의 일자')),
                ('is_loc_agree', models.BooleanField(default=True, null=True, verbose_name='위치 정보 이용 동의 여부')),
                ('date_loc_agree', models.DateTimeField(auto_now_add=True, null=True, verbose_name='위치 정보 이용 동의 일자')),
                ('is_over_fourteen', models.BooleanField(default=True, null=True, verbose_name='14세 이상 여부')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_image_upload, verbose_name='프로필 사진')),
                ('introduction', models.CharField(blank=True, max_length=100, null=True, verbose_name='자기소개')),
                ('pioneer_count', models.PositiveIntegerField(default=0, verbose_name='계정 개척 수')),
            ],
            options={
                'verbose_name': '1.1 회원 기본 정보',
                'verbose_name_plural': '1.1 회원 기본 정보',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='피드좋아요 pk')),
            ],
            options={
                'verbose_name': '1.3 회원 피드 좋아요 정보',
                'verbose_name_plural': '1.3 회원 피드 좋아요 정보',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='피드보관함 pk')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '1.2 회원 피드 보관 정보',
                'verbose_name_plural': '1.2 회원 피드 보관 정보',
            },
        ),
    ]
