# Generated by Django 3.1.5 on 2023-02-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accountparty_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='파티명'),
        ),
    ]
