# Generated by Django 3.1.5 on 2023-01-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20230109_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopscore',
            name='fooiyti_a_percentage',
        ),
        migrations.RemoveField(
            model_name='shopscore',
            name='fooiyti_c_percentage',
        ),
        migrations.RemoveField(
            model_name='shopscore',
            name='fooiyti_e_percentage',
        ),
        migrations.RemoveField(
            model_name='shopscore',
            name='fooiyti_f_percentage',
        ),
        migrations.RemoveField(
            model_name='shopscore',
            name='fooiyti_feed_count',
        ),
        migrations.RemoveField(
            model_name='shopscore',
            name='fooiyti_i_percentage',
        ),
        migrations.RemoveField(
            model_name='shopscore',
            name='fooiyti_n_percentage',
        ),
        migrations.RemoveField(
            model_name='shopscore',
            name='fooiyti_s_percentage',
        ),
        migrations.RemoveField(
            model_name='shopscore',
            name='fooiyti_t_percentage',
        ),
    ]
