# Generated by Django 3.1.5 on 2023-01-14 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20230115_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopFooiyti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fooiyti', models.CharField(blank=True, choices=[('ENTC', 'ENTC'), ('ENTA', 'ENTA'), ('ENFA', 'ENFA'), ('ENFC', 'ENFC'), ('ESTC', 'ESTC'), ('ESTA', 'ESTA'), ('ESFA', 'ESFA'), ('ESFC', 'ESFC'), ('INTC', 'INTC'), ('INTA', 'INTA'), ('INFA', 'INFA'), ('INFC', 'INFC'), ('ISTC', 'ISTC'), ('ISTA', 'ISTA'), ('ISFA', 'ISFA'), ('ISFC', 'ISFC')], max_length=4, null=True, verbose_name='FOOIYTI')),
                ('feed_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='푸이티아이 평가 개수')),
                ('e_percentage', models.PositiveSmallIntegerField(blank=True, default=50, null=True)),
                ('i_percentage', models.PositiveSmallIntegerField(blank=True, default=50, null=True)),
                ('s_percentage', models.PositiveSmallIntegerField(blank=True, default=50, null=True)),
                ('n_percentage', models.PositiveSmallIntegerField(blank=True, default=50, null=True)),
                ('t_percentage', models.PositiveSmallIntegerField(blank=True, default=50, null=True)),
                ('f_percentage', models.PositiveSmallIntegerField(blank=True, default=50, null=True)),
                ('a_percentage', models.PositiveSmallIntegerField(blank=True, default=50, null=True)),
                ('c_percentage', models.PositiveSmallIntegerField(blank=True, default=50, null=True)),
                ('shop', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'verbose_name': '2.1.4 매장 정보 (푸이티아이)',
                'verbose_name_plural': '2.1.4 매장 정보 (푸이티아이)',
            },
        ),
    ]
