# Generated by Django 3.1.5 on 2023-01-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_shopfooiyti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopfooiyti',
            name='a_percentage',
            field=models.SmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopfooiyti',
            name='c_percentage',
            field=models.SmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopfooiyti',
            name='e_percentage',
            field=models.SmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopfooiyti',
            name='f_percentage',
            field=models.SmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopfooiyti',
            name='i_percentage',
            field=models.SmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopfooiyti',
            name='n_percentage',
            field=models.SmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopfooiyti',
            name='s_percentage',
            field=models.SmallIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopfooiyti',
            name='t_percentage',
            field=models.SmallIntegerField(blank=True, default=50, null=True),
        ),
    ]
