# Generated by Django 3.1.5 on 2023-01-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_auto_20230116_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopscore',
            name='feed_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='피드 개수'),
        ),
    ]
