# Generated by Django 3.1.5 on 2022-12-14 12:01

import archives.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='광고 pk')),
                ('type', models.CharField(blank=True, choices=[('BANNER', '배너'), ('FEED', '피드')], max_length=10, null=True, verbose_name='광고 유형')),
                ('advertiser', models.CharField(blank=True, help_text='내부 광고 : 푸이', max_length=20, null=True, verbose_name='광고주')),
                ('title', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='광고 타이틀')),
                ('is_exposure', models.BooleanField(blank=True, default=True, null=True, verbose_name='광고 공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '3.7 광고 정보',
                'verbose_name_plural': '3.7 광고 정보',
            },
        ),
        migrations.CreateModel(
            name='Fooiyti',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='푸이티아이 pk')),
                ('fooiyti', models.CharField(blank=True, choices=[('ENTC', 'ENTC'), ('ENTA', 'ENTA'), ('ENFA', 'ENFA'), ('ENFC', 'ENFC'), ('ESTC', 'ESTC'), ('ESTA', 'ESTA'), ('ESFA', 'ESFA'), ('ESFC', 'ESFC'), ('INTC', 'INTC'), ('INTA', 'INTA'), ('INFA', 'INFA'), ('INFC', 'INFC'), ('ISTC', 'ISTC'), ('ISTA', 'ISTA'), ('ISFA', 'ISFA'), ('ISFC', 'ISFC')], max_length=4, null=True, verbose_name='푸이티아이')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True, verbose_name='푸이티아이 별명')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='푸이티아이 설명')),
            ],
            options={
                'verbose_name': '3.2 푸이티아이 정보',
                'verbose_name_plural': '3.2 푸이티아이 정보',
            },
        ),
        migrations.CreateModel(
            name='FooiytiQuestion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='푸이티아이 질문지 pk')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='ex) 1', verbose_name='정렬 순서')),
                ('question', models.CharField(blank=True, max_length=200, null=True, verbose_name='질문')),
                ('is_multi_answer', models.BooleanField(default=False, verbose_name='답 복수 선택 가능')),
                ('answer_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='답 후보 1')),
                ('result_1', models.JSONField(blank=True, null=True, verbose_name='답 결과 1')),
                ('answer_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='답 후보 2')),
                ('result_2', models.JSONField(blank=True, null=True, verbose_name='답 결과 2')),
                ('answer_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='답 후보 3')),
                ('result_3', models.JSONField(blank=True, null=True, verbose_name='답 결과 3')),
                ('answer_4', models.CharField(blank=True, max_length=100, null=True, verbose_name='답 후보 4')),
                ('result_4', models.JSONField(blank=True, null=True, verbose_name='답 결과 4')),
            ],
            options={
                'verbose_name': '3.3 푸이티아이 질문지 정보',
                'verbose_name_plural': '3.3 푸이티아이 질문지 정보',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='공지사항 정보 pk')),
                ('title', models.CharField(blank=True, help_text='긴급 공지 사용 시 작성', max_length=30, null=True, verbose_name='공지사항 제목')),
                ('content', models.CharField(blank=True, help_text='긴급 공지 사용 시 작성', max_length=200, null=True, verbose_name='공지사항 내용')),
                ('is_emergency', models.BooleanField(blank=True, default=False, null=True, verbose_name='긴급공지 여부')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=100, null=True, verbose_name='공지사항 순서')),
                ('is_exposure', models.BooleanField(blank=True, default=True, null=True, verbose_name='공지사항 공개 여부')),
                ('date_event_start', models.DateTimeField(blank=True, null=True, verbose_name='공지사항 시작일')),
                ('date_event_finish', models.DateTimeField(blank=True, null=True, verbose_name='공지사항 종료일')),
            ],
            options={
                'verbose_name': '3.5 공지사항 정보',
                'verbose_name_plural': '3.5 공지사항 정보',
            },
        ),
        migrations.CreateModel(
            name='TasteEvaluation',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='맛 평가 pk')),
                ('type', models.CharField(blank=True, choices=[('border', '테두리 있는 이모지'), ('no_border', '테두리 없는 이모지')], max_length=10, null=True)),
                ('score', models.PositiveSmallIntegerField(default=10, help_text='ex) 10', verbose_name='점수')),
            ],
            options={
                'verbose_name': '3.4 맛 평가 정보',
                'verbose_name_plural': '3.4 맛 평가 정보',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=15, null=True, verbose_name='버전')),
                ('os', models.CharField(blank=True, max_length=10, null=True, verbose_name='OS')),
                ('change_history', models.CharField(blank=True, max_length=500, null=True, verbose_name='변경 내역')),
                ('is_update_required', models.BooleanField(default=False, verbose_name='강제 업데이트 필요 유무')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='버전 업데이트 일시')),
            ],
            options={
                'verbose_name': '3.6 버전 정보',
                'verbose_name_plural': '3.6 버전 정보',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='문의 pk')),
                ('type', models.CharField(blank=True, choices=[('IMP', '개선 사항'), ('FR', '기능 추가 요청'), ('BUG', '버그 신고'), ('AC', '계정 관련'), ('AD', '광고 제의'), ('ETC', '기타 피드백')], max_length=10, null=True, verbose_name='문의 유형')),
                ('content', models.CharField(blank=True, max_length=500, null=True, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion', to=settings.AUTH_USER_MODEL, verbose_name='문의자')),
            ],
            options={
                'verbose_name': '3.8 문의 정보',
                'verbose_name_plural': '3.8 문의 정보',
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='푸시 알림 pk')),
                ('type', models.CharField(choices=[('PIONEER', '개척'), ('STORAGE', '보관'), ('LIKE', '좋아요'), ('COMMENT', '댓글')], default='PIONEER', max_length=10, null=True, verbose_name='푸시 타입')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='푸시 알림 제목')),
                ('content', models.CharField(blank=True, max_length=300, null=True, verbose_name='푸시 알림 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_notification', to=settings.AUTH_USER_MODEL, verbose_name='푸시 알림 계정')),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_notification', to='feeds.feed', verbose_name='피드')),
                ('pioneer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_notification', to='feeds.pioneer', verbose_name='개척')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='푸시 받는 계정')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='푸시 보내는 계정')),
            ],
            options={
                'verbose_name': '3.10 푸시 알림 정보',
                'verbose_name_plural': '3.10 푸시 알림 정보',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='이미지 pk')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='ex) 1', verbose_name='정렬 순서')),
                ('type', models.CharField(choices=[('OB', '온보딩'), ('DPI', '기본 프로필 이미지'), ('NSI', '주변 매장 없을 때 이미지'), ('NSS', '검색 매장 없을 때 이미지'), ('NSF', '보관함이 비었을 때 이미지'), ('NMF', '마이페이지 피드가 없을 때 이미지'), ('P', '개척'), ('R', '기록'), ('F', '피드'), ('TE', '맛 평가'), ('N', '공지사항'), ('AD', '광고'), ('FR', '푸이티아이 결과')], default='', max_length=5, verbose_name='이미지 타입')),
                ('image', models.ImageField(blank=True, upload_to=archives.models.archives_image_upload_url, verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to=settings.AUTH_USER_MODEL)),
                ('advertisement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='archives.advertisement')),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='feeds.feed')),
                ('fooiyti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='archives.fooiyti')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='shops.menu')),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='archives.notice')),
                ('pioneer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='feeds.pioneer')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='feeds.record')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='shops.shop')),
                ('taste_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='archives.tasteevaluation')),
            ],
            options={
                'verbose_name': '3.1 아카이브 이미지 정보',
                'verbose_name_plural': '3.1 아카이브 이미지 정보',
            },
        ),
        migrations.CreateModel(
            name='AddressCluster',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='주소 클러스터 pk')),
                ('depth', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='뎁스')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='뎁스 명')),
                ('longitude', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='경도')),
                ('latitude', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='위도')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='매장 수')),
                ('parent_depth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_depth', to='archives.addresscluster', verbose_name='상위 뎁스 정보')),
            ],
            options={
                'verbose_name': '3.9 주소 클러스터 정보',
                'verbose_name_plural': '3.9 주소 클러스터 정보',
            },
        ),
    ]
