# Generated by Django 3.1.5 on 2023-02-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_accountparty_created_at"),
        ("archives", "0002_auto_20230131_1323"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushnotification",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="push_notification",
                to="accounts.party",
                verbose_name="파티",
            ),
        ),
        migrations.AlterField(
            model_name="pushnotification",
            name="type",
            field=models.CharField(
                choices=[
                    ("PIONEER", "개척"),
                    ("STORAGE", "보관"),
                    ("LIKE", "좋아요"),
                    ("COMMENT", "댓글"),
                    ("RANK", "랭크"),
                    ("PARTY", "파티"),
                    ("OVERALL_NOTICE", "전체공지"),
                ],
                default="PIONEER",
                max_length=20,
                null=True,
                verbose_name="푸시 타입",
            ),
        ),
    ]
