# Generated by Django 3.1.5 on 2023-02-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_pushnotification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('OB', '온보딩'), ('DPI', '기본 프로필 이미지'), ('NSI', '주변 매장 없을 때 이미지'), ('NSS', '검색 매장 없을 때 이미지'), ('NSF', '보관함이 비었을 때 이미지'), ('NMF', '마이페이지 피드가 없을 때 이미지'), ('P', '개척'), ('R', '기록'), ('F', '피드'), ('TE', '맛 평가'), ('N', '공지사항'), ('AD', '광고'), ('FR', '푸이티아이 결과'), ('RI', '랭커 푸시 알림 이미지')], default='', max_length=5, verbose_name='이미지 타입'),
        ),
    ]
