from django.db import transaction

from rest_framework import status
from rest_framework.response import Response


menu_list = {
    ######### 돈까스 #########
    "돈카츠": ["CUTLET", "JAPANESE"],
    "안심카츠": ["CUTLET", "JAPANESE"],
    "등심카츠": ["CUTLET", "JAPANESE"],
    "카츠산도": ["CUTLET", "JAPANESE"],
    "모듬카츠": ["CUTLET", "JAPANESE"],
    "돈까스": ["CUTLET"],
    "치즈돈까스": ["CUTLET"],
    "고구마치즈돈까스": ["CUTLET"],
    "경양식돈까스": ["CUTLET"],
    "카레돈까스": ["CUTLET"],
    "옛날돈까스": ["CUTLET"],
    "로제돈까스": ["CUTLET"],
    "돈까스정식": ["CUTLET"],
    "치즈롤까스": ["CUTLET"],
    "등심돈까스": ["CUTLET"],
    "안심돈까스": ["CUTLET"],
    "치즈롤까스정식": ["CUTLET"],
    "등심돈까스정식": ["CUTLET"],
    "안심돈까스정식": ["CUTLET"],
    "모짜렐라치즈돈까스": ["CUTLET"],
    "치즈돈가스": ["CUTLET"],
    "고구마치즈돈가스": ["CUTLET"],
    "경양식돈가스": ["CUTLET"],
    "카레돈가스": ["CUTLET"],
    "옛날돈가스": ["CUTLET"],
    "로제돈가스": ["CUTLET"],
    "돈가스정식": ["CUTLET"],
    "등심돈가스": ["CUTLET"],
    "안심돈가스": ["CUTLET"],
    "치즈롤가스정식": ["CUTLET"],
    "등심돈가스정식": ["CUTLET"],
    "안심돈가스정식": ["CUTLET"],
    "모짜렐라치즈돈가스 ": ["CUTLET"],
    "생선까스": ["CUTLET"],
    "로스까스": ["CUTLET"],
    "안심까스": ["CUTLET"],
    "모둠까스": ["CUTLET"],
    "생선가스": ["CUTLET"],
    "로스가스": ["CUTLET"],
    "안심가스": ["CUTLET"],
    "모둠가스": ["CUTLET"],
    "김치나베돈까스": ["CUTLET"],
    "김치나베돈가스 ": ["CUTLET"],
    ######### 회/초밥 #########
    "모듬회": ["RAW/SUSHI"],
    "모듬회세트": ["RAW/SUSHI"],
    "모듬초밥": ["RAW/SUSHI"],
    "매운탕": ["RAW/SUSHI"],
    "우럭매운탕": ["RAW/SUSHI"],
    "활어회덮밥": ["RAW/SUSHI"],
    "활어회": ["RAW/SUSHI"],
    "광어": ["RAW/SUSHI"],
    "광어회": ["RAW/SUSHI"],
    "방어": ["RAW/SUSHI"],
    "방어회": ["RAW/SUSHI"],
    "도다리세꼬시": ["RAW/SUSHI"],
    "세꼬시": ["RAW/SUSHI"],
    "도미": ["RAW/SUSHI"],
    "물회": ["RAW/SUSHI"],
    "제철모듬회": ["RAW/SUSHI"],
    "참돔": ["RAW/SUSHI"],
    "참돔회": ["RAW/SUSHI"],
    ######### 일식 #########
    "토리빠이탄라멘": ["JAPANESE"],
    "토리빠이탄": ["JAPANESE"],
    "카라빠이탄라멘": ["JAPANESE"],
    "카라빠이탄": ["JAPANESE"],
    "쇼유라멘": ["JAPANESE"],
    "시오라멘": ["JAPANESE"],
    "치킨가라아게": ["JAPANESE"],
    "시오라멘": ["JAPANESE"],
    "쇼유라멘": ["JAPANESE"],
    "규동": ["JAPANESE"],
    "부타동": ["JAPANESE"],
    "차슈동": ["JAPANESE"],
    "카라이라멘": ["JAPANESE"],
    "돈코츠라멘": ["JAPANESE"],
    "돈고츠라멘": ["JAPANESE"],
    "마제소바": ["JAPANESE"],
    "아부라소바": ["JAPANESE"],
    "미도리카메": ["JAPANESE"],
    "키츠네": ["JAPANESE"],
    "키요마사": ["JAPANESE"],
    "츠케멘": ["JAPANESE"],
    "라멘": ["JAPANESE"],
    "타코야끼": ["JAPANESE"],
    ######### 중식 #########
    "오향장육": ["CHINESE"],
    "멘보샤": ["CHINESE"],
    "자장면": ["CHINESE"],
    "짜장면": ["CHINESE"],
    "삼선짜장면": ["CHINESE"],
    "삼선자장면": ["CHINESE"],
    "사천자장면": ["CHINESE"],
    "사천짜장면": ["CHINESE"],
    "삼선짬뽕": ["CHINESE"],
    "짬뽕": ["CHINESE"],
    "짜장": ["CHINESE"],
    "고기짬뽕": ["CHINESE"],
    "유산슬": ["CHINESE"],
    "칠리새우": ["CHINESE"],
    "고추잡채": ["CHINESE"],
    "해파리냉채": ["CHINESE"],
    "탕수육": ["CHINESE"],
    "깐풍기": ["CHINESE"],
    "게살스프": ["CHINESE"],
    "중화비빔밥": ["CHINESE"],
    "간짜장": ["CHINESE"],
    "짜장밥": ["CHINESE"],
    "마라탕": ["CHINESE", "ASIAN"],
    "마라훠궈": ["CHINESE", "ASIAN"],
    "마라샹궈": ["CHINESE", "ASIAN"],
    "꿔바로우": ["CHINESE", "ASIAN"],
    ######### 치킨 #########
    "치킨": ["CHICKEN"],
    "후라이드치킨": ["CHICKEN"],
    "양념치킨": ["CHICKEN"],
    "반반치킨": ["CHICKEN"],
    "순살치킨": ["CHICKEN"],
    "뼈치킨": ["CHICKEN"],
    "간장치킨": ["CHICKEN"],
    "옛날통닭": ["CHICKEN"],
    "바베큐치킨": ["CHICKEN"],
    "시골통닭": ["CHICKEN"],
    "양념통닭": ["CHICKEN"],
    "후라이드통닭": ["CHICKEN"],
    "반반통닭": ["CHICKEN"],
    "마늘치킨": ["CHICKEN"],
    "마늘통닭": ["CHICKEN"],
    "슈프림치킨": ["CHICKEN"],
    ######### 한식 #########
    "만두전골": ["KOREAN"],
    "조개전골": ["KOREAN"],
    "소고기만두전골": ["KOREAN"],
    "소고기전골": ["KOREAN"],
    "샤브샤브": ["KOREAN"],
    "김치찌개": ["KOREAN"],
    "된짱찌개 ": ["KOREAN"],
    "제육볶음": ["KOREAN"],
    "부대찌개": ["KOREAN"],
    "쌈밥": ["KOREAN"],
    "김치두루치기": ["KOREAN"],
    ######### 해산물 #########
    "꽃게탕": ["SEAFOOD", "KOREAN"],
    "간장게장": ["SEAFOOD", "KOREAN"],
    "양념게장": ["SEAFOOD", "KOREAN"],
    "대게": ["SEAFOOD", "KOREAN"],
    "대게찜": ["SEAFOOD", "KOREAN"],
    "대게세트": ["SEAFOOD", "KOREAN"],
    "홍게세트": ["SEAFOOD", "KOREAN"],
    "홍게": ["SEAFOOD", "KOREAN"],
    "킹크랩": ["SEAFOOD", "KOREAN"],
    "낙지찜": ["SEAFOOD", "KOREAN"],
    "아구찜": ["SEAFOOD", "KOREAN"],
    "꽃게찜": ["SEAFOOD", "KOREAN"],
    "꽃게탕": ["SEAFOOD", "KOREAN"],
    "전복찜": ["SEAFOOD"],
    "전복버터구이": ["SEAFOOD"],
    "낙지찜": ["SEAFOOD"],
    "낙지탕탕이": ["SEAFOOD"],
    "멍게": ["SEAFOOD"],
    "석화": ["SEAFOOD"],
    "조개구이": ["SEAFOOD"],
    "치즈조개구이": ["SEAFOOD"],
    "꽃게": ["SEAFOOD"],
    "해산물": ["SEAFOOD"],
    ######### 국수 #########
    "쌀국수": ["NOODLE"],
    "칼국수": ["NOODLE"],
    "김치말이국수": ["NOODLE"],
    "콩국수": ["NOODLE"],
    "잔치국수": ["NOODLE"],
    "막국수": ["NOODLE"],
    "비밈막국수": ["NOODLE"],
    "물막국수": ["NOODLE"],
    "메밀국수": ["NOODLE"],
    "육개장칼국수": ["NOODLE"],
    "닭칼국수": ["NOODLE"],
    "닭한마리칼국수": ["NOODLE"],
    "샤브칼국수": ["NOODLE"],
    "버섯칼국수": ["NOODLE"],
    "평양냉면": ["KOREAN", "NOODLE"],
    ######### 분식 #########
    "떡볶이": ["SNACKBAR"],
    "라볶이": ["SNACKBAR"],
    "짜장떡볶이": ["SNACKBAR"],
    "로제떡볶이": ["SNACKBAR"],
    "치즈떡볶이": ["SNACKBAR"],
    "쫄면": ["SNACKBAR"],
    "부대라면": ["SNACKBAR"],
    "라면": ["SNACKBAR"],
    "순대": ["SNACKBAR"],
    "김밥": ["SNACKBAR"],
    "어묵": ["SNACKBAR"],
    "오뎅": ["SNACKBAR"],
    "꼬마김밥": ["SNACKBAR"],
    ######### 햄버거 #########
    "햄버거": ["BURGER"],
    "버거": ["BURGER"],
    "치즈버거": ["BURGER"],
    "더블버거": ["BURGER"],
    "베이컨치즈버거": ["BURGER"],
    "치킨버거": ["BURGER"],
    "더블패티버거": ["BURGER"],
    "클래식버거": ["BURGER"],
    "더블클래식버거": ["BURGER"],
    "burger": ["BURGER"],
    ######### 피자 #########
    "치즈피자": ["PIZZA"],
    "페퍼로니피자": ["PIZZA"],
    "콤비네이션피자": ["PIZZA"],
    "고구마피자": ["PIZZA"],
    "핫치킨피자": ["PIZZA"],
    "불고기피자": ["PIZZA"],
    "포테이토피자": ["PIZZA"],
    "나폴리피자": ["PIZZA"],
    "고르곤졸라피자": ["PIZZA"],
    "까르보네피자": ["PIZZA"],
    "파인애플피자": ["PIZZA"],
    "하와이안피자    ": ["PIZZA"],
    ######### 양식 #########
    "파스타": ["WESTERN"],
    "스파게티": ["WESTERN"],
    "까르보나라": ["WESTERN"],
    "토마토스파게티": ["WESTERN"],
    "토마토파스타": ["WESTERN"],
    "오일파스타": ["WESTERN"],
    "볼로네제": ["WESTERN"],
    "리조또": ["WESTERN"],
    "해산물토마토파스타": ["WESTERN"],
    "베이컨파스타": ["WESTERN"],
    "베이컨크림파스타": ["WESTERN"],
    "명란파스타": ["WESTERN"],
    "명란오일스파케티": ["WESTERN"],
    "로제파스타": ["WESTERN"],
    "스테이크": ["WESTERN"],
    "등심스테이크": ["WESTERN"],
    "안심스테이크": ["WESTERN"],
    "알리오올리오": ["WESTERN"],
    "찹스테이크": ["WESTERN"],
    ######### 고기/구이 #########
    "삼겹살": ["MEAT/ROAST"],
    "꽃삼겹살": ["MEAT/ROAST"],
    "숙성삼겹살": ["MEAT/ROAST"],
    "목살": ["MEAT/ROAST"],
    "가브리살": ["MEAT/ROAST"],
    "돼지껍데기": ["MEAT/ROAST"],
    "항정살": ["MEAT/ROAST"],
    "갈비": ["MEAT/ROAST"],
    "소갈비": ["MEAT/ROAST"],
    "돼지갈비": ["MEAT/ROAST"],
    "한우살치살": ["MEAT/ROAST"],
    "한우등심": ["MEAT/ROAST"],
    "한우안심": ["MEAT/ROAST"],
    "한우살치살": ["MEAT/ROAST"],
    "생갈비": ["MEAT/ROAST"],
    "생삼겹살": ["MEAT/ROAST"],
    "한우꽃등심": ["MEAT/ROAST"],
    "LA갈비": ["MEAT/ROAST"],
    "치마살": ["MEAT/ROAST"],
    "대창": ["MEAT/ROAST"],
    "곱창": ["MEAT/ROAST"],
    "막창": ["MEAT/ROAST"],
    "한우곱창": ["MEAT/ROAST"],
    ######### 족발/보쌈 #########
    "족발": ["PETTITOES/BOSSAM"],
    "보쌈": ["PETTITOES/BOSSAM"],
    "족발+보쌈": ["PETTITOES/BOSSAM"],
    "불족발": ["PETTITOES/BOSSAM"],
    "족발보쌈": ["PETTITOES/BOSSAM"],
    "보쌈+족발": ["PETTITOES/BOSSAM"],
    "냉채족발": ["PETTITOES/BOSSAM"],
    "매운족발": ["PETTITOES/BOSSAM"],
    "마늘보쌈": ["PETTITOES/BOSSAM"],
    "마늘족발": ["PETTITOES/BOSSAM"],
    ######### 아시안 #########
    "쌀국수": ["ASIAN"],
    "파인애플볶음밥": ["ASIAN"],
    "차돌양지쌀국수": ["ASIAN"],
    "양지쌀국수": ["ASIAN"],
    "차돌쌀국수": ["ASIAN"],
    "월남쌈": ["ASIAN"],
    "소고기쌀국수": ["ASIAN"],
    "매운소고기쌀국수": ["ASIAN"],
    "분짜": ["ASIAN"],
    "히노이볶음면": ["ASIAN"],
    "하노이월남쌈": ["ASIAN"],
    "분짜월남쌈": ["ASIAN"],
    "마라쌀국수": ["ASIAN"],
    "닭쌀국수": ["ASIAN"],
    "짜조": ["ASIAN"],
    "하노이짜조": ["ASIAN"],
    ######### 토스트/샌드위치 #########
    "햄치즈토스트": ["TOAST/SANDWICH"],
    "햄스페셜토스트": ["TOAST/SANDWICH"],
    "베이컨토스트": ["TOAST/SANDWICH"],
    "피자토스트": ["TOAST/SANDWICH"],
    "토스트": ["TOAST/SANDWICH"],
    "베이컨포테이토피자토스트": ["TOAST/SANDWICH"],
    "베이컨포테이토토스트": ["TOAST/SANDWICH"],
    "감자토스트": ["TOAST/SANDWICH"],
    "베이글": ["TOAST/SANDWICH"],
    "치즈베이글": ["TOAST/SANDWICH"],
    "베이컨치즈베이글": ["TOAST/SANDWICH"],
    "샌드위치": ["TOAST/SANDWICH"],
    "루꼴라샌드위치": ["TOAST/SANDWICH"],
    "쉬림프번샌드위치": ["TOAST/SANDWICH"],
    "에그마요샌드위치": ["TOAST/SANDWICH"],
    "에그샌드위치    ": ["TOAST/SANDWICH"],
    ######### 도시락/죽 #########
    "동지팥죽": ["LUNCHBOX/PORRIDGE"],
    "낙치김치죽": ["LUNCHBOX/PORRIDGE"],
    "전복죽": ["LUNCHBOX/PORRIDGE"],
    "쇠고기야채죽": ["LUNCHBOX/PORRIDGE"],
    "단호박죽": ["LUNCHBOX/PORRIDGE"],
    "트러플전복죽": ["LUNCHBOX/PORRIDGE"],
    "전복내장죽": ["LUNCHBOX/PORRIDGE"],
    "삼계죽": ["LUNCHBOX/PORRIDGE"],
    "불낙죽": ["LUNCHBOX/PORRIDGE"],
    "쇠고기야채죽": ["LUNCHBOX/PORRIDGE"],
    "쇠고기버섯죽": ["LUNCHBOX/PORRIDGE"],
    "새우죽": ["LUNCHBOX/PORRIDGE"],
    "해물죽": ["LUNCHBOX/PORRIDGE"],
    "참치야채죽": ["LUNCHBOX/PORRIDGE"],
    "쇠고기미역죽": ["LUNCHBOX/PORRIDGE"],
    "녹두죽": ["LUNCHBOX/PORRIDGE"],
    ######### 샐러드 #########
    "샐러드": ["SALAD"],
    "리코타치즈샐러드": ["SALAD"],
    "파인애플새우샐러드": ["SALAD"],
    "포케": ["SALAD"],
    "현미밥포케": ["SALAD"],
    "닭다리살샐러드": ["SALAD"],
    "달가슴살샐러드": ["SALAD"],
    "훈제오리포케": ["SALAD"],
    "목살포케": ["SALAD"],
    "그릴드훈제오리포케": ["SALAD"],
    "그릴드목살포케": ["SALAD"],
    "쉬림프포케": ["SALAD"],
    "연어포케": ["SALAD"],
    "불고기포케": ["SALAD"],
    "수비드닭가슴살샐러드": ["SALAD"],
    "훈제오리샐러드": ["SALAD"],
    "그리드훈제오리샐러드": ["SALAD"],
    "연어샐러드": ["SALAD"],
    "쉬림프샐러드": ["SALAD"],
    "불고기샐러드 ": ["SALAD"],
    "풀드포크포케": ["SALAD"],
    "포크포케": ["SALAD"],
}

# 메뉴명으로 가기

franchise_list = {
    "치킨더치킨": ["CHICKEN"],
    "깻잎치킨": ["CHICKEN"],
    "ONE&TWO깻잎치킨": ["CHICKEN"],
    "교촌치킨": ["CHICKEN"],
    "비비큐치킨": ["CHICKEN"],
    "BBQ치킨": ["CHICKEN"],
    "bbq치킨": ["CHICKEN"],
    "썬더치킨": ["CHICKEN"],
    "처갓집양념치킨": ["CHICKEN"],
    "굽네치킨": ["CHICKEN"],
    "수준이다른치킨": ["CHICKEN"],
    "네네치킨": ["CHICKEN"],
    "지코바양념치킨": ["CHICKEN"],
    "지코바": ["CHICKEN"],
    "호식이두마리치킨": ["CHICKEN"],
    "호식이두마리": ["CHICKEN"],
    "맥시칸치킨": ["CHICKEN"],
    "피자나라치킨공주": ["CHICKEN"],
    "멕시칸치킨": ["CHICKEN"],
    "치킨플러스": ["CHICKEN"],
    "행복치킨": ["CHICKEN"],
    "티바두마리치킨": ["CHICKEN"],
    "땅땅치킨": ["CHICKEN"],
    "바른치킨": ["CHICKEN"],
    "보드람치킨": ["CHICKEN"],
    "깐부치킨": ["CHICKEN"],
    "둘둘치킨": ["CHICKEN"],
    "치킨매니아": ["CHICKEN"],
    "코리안바베큐": ["CHICKEN"],
    "누룽지통닭구이": ["CHICKEN"],
    "굽네치킨": ["CHICKEN"],
    "푸라닭": ["CHICKEN"],
    "60계치킨": ["CHICKEN"],
    "BHC": ["CHICKEN"],
    "노랑통닭": ["CHICKEN"],
    "자담치킨": ["CHICKEN"],
    "처갓집양념치킨": ["CHICKEN"],
    "호식이두마리치킨": ["CHICKEN"],
    "바른치킨": ["CHICKEN"],
    "아웃닭": ["CHICKEN"],
    "페리카나": ["CHICKEN"],
    "또붕이통닭": ["CHICKEN"],
    "부어치킨": ["CHICKEN"],
    "땅땅치킨": ["CHICKEN"],
    "또레오레": ["CHICKEN"],
    "오븐마루": ["CHICKEN"],
    "순수치킨": ["CHICKEN"],
    "훌랄라치킨": ["CHICKEN"],
    "디디치킨": ["CHICKEN"],
    "마파치킨": ["CHICKEN"],
    "웰덤치킨": ["CHICKEN"],
    "맘스터치": ["BURGER"],
    "롯데리아": ["BURGER"],
    "버거킹": ["BURGER"],
    "맥도널드": ["BURGER"],
    "KFC": ["BURGER"],
    "파파이스": ["BURGER"],
    "다운타우너": ["BURGER"],
    "피자스쿨": ["PIZZA"],
    "오구쌀피자": ["PIZZA"],
    "59쌀피자": ["PIZZA"],
    "피자마루": ["PIZZA"],
    "미스터피자": ["PIZZA"],
    "피자헛": ["PIZZA"],
    "도미노피자": ["PIZZA"],
    "파파존스": ["PIZZA"],
    "피자에땅": ["PIZZA"],
    "피자헤븐": ["PIZZA"],
    "피자알볼로": ["PIZZA"],
    "뽕뜨락피자": ["PIZZA"],
    "피자알볼로": ["PIZZA"],
    "본도시락": ["LUNCHBOX/PORRIDGE"],
    "오봉도시락": ["LUNCHBOX/PORRIDGE"],
    "토마토도시락 ": ["LUNCHBOX/PORRIDGE"],
    "한솥": ["LUNCHBOX/PORRIDGE"],
    "본죽": ["LUNCHBOX/PORRIDGE"],
    "참죽": ["LUNCHBOX/PORRIDGE"],
    "한끼한죽": ["LUNCHBOX/PORRIDGE"],
    "죽이야기": ["LUNCHBOX/PORRIDGE"],
    "죽이요": ["LUNCHBOX/PORRIDGE"],
    "죽~이요": ["LUNCHBOX/PORRIDGE"],
    "맛깔참죽": ["LUNCHBOX/PORRIDGE"],
    "본초맘죽": ["LUNCHBOX/PORRIDGE"],
    "현죽": ["LUNCHBOX/PORRIDGE"],
    "본앤본": ["LUNCHBOX/PORRIDGE"],
    "바푸리죽앤즙": ["LUNCHBOX/PORRIDGE"],
    "기운찬식탁": ["LUNCHBOX/PORRIDGE"],
    "수라죽": ["LUNCHBOX/PORRIDGE"],
    "에그드랍": ["TOAST/SANDWICH"],
    "이삭토스트": ["TOAST/SANDWICH"],
    "이삭": ["TOAST/SANDWICH"],
    "에그존": ["TOAST/SANDWICH"],
    "EGGZONE": ["TOAST/SANDWICH"],
    "EGGDROP": ["TOAST/SANDWICH"],
    "샌드리아": ["TOAST/SANDWICH"],
    "SUBWAY": ["TOAST/SANDWICH", "SALAD"],
    "서브웨이": ["TOAST/SANDWICH", "SALAD"],
    "써브웨이": ["TOAST/SANDWICH", "SALAD"],
    "퀴즈노스": ["TOAST/SANDWICH", "SALAD"],
    "리나스샌드위치": ["TOAST/SANDWICH", "SALAD"],
    "샐러디": ["TOAST/SANDWICH", "SALAD"],
    "샌드리아": ["TOAST/SANDWICH", "SALAD"],
    "샐러드박스": ["SALAD"],
    "SALADBOX": ["SALAD"],
    "투고샐러드": ["SALAD"],
    "잇샐러드": ["SALAD"],
    "갓샐러드": ["SALAD"],
    "샐러드밥": ["SALAD"],
    "아메리칸트레이": ["SALAD"],
}

# 매장명으로 가기

shop_domains = {
    "돈까스": ["CUTLET"],
    "밥버거": ["KOREAN"],
    "핫도그": ["SNACKBAR"],
    "분식": ["SNACKBAR"],
    "김밥": ["SNACKBAR"],
    "버거": ["BURGER"],
    "BURGER": ["BURGER"],
    "파스타": ["WESTERN"],
    "PASTA": ["WESTERN"],
    "피자": ["PIZZA"],
    "족발": ["PETTITOES/BOSSAM"],
    "마라": ["CHINESE", "ASIAN"],
}

shop_domains_keys = list(shop_domains.keys())


def check_shop_category(shop_name, menu_name):
    category = []
    for shop_domains_key in shop_domains_keys:
        if shop_domains_key in shop_name:
            category = shop_domains[shop_domains_key]
            return category

    for shop_domains_key in shop_domains_keys:
        if shop_domains_key in menu_name:
            category = shop_domains[shop_domains_key]
            return category

    if franchise_list.get(shop_name):
        category = franchise_list.get(shop_name)

    elif menu_list.get(menu_name):
        category = menu_list.get(menu_name)

    return category
