# Generated by Django 3.1.5 on 2023-02-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_feedparty_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pioneer',
            name='subscribe_party',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='구독신청한 파티'),
        ),
    ]
