# Generated by Django 3.1.5 on 2023-01-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='type',
            field=models.CharField(blank=True, choices=[('IMP', '개선 사항'), ('FR', '기능 추가 요청'), ('BUG', '버그 신고'), ('AC', '계정 관련'), ('AD', '광고 제의'), ('ETC', '기타 피드백'), ('TIP_OFF', '메뉴판 정보 오류 제보')], max_length=10, null=True, verbose_name='문의 유형'),
        ),
    ]
