# Generated by Django 3.1.5 on 2023-02-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0003_auto_20230207_1758"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushnotification",
            name="type",
            field=models.CharField(
                choices=[
                    ("PIONEER", "개척"),
                    ("STORAGE", "보관"),
                    ("LIKE", "좋아요"),
                    ("COMMENT", "댓글"),
                    ("RANK", "랭크"),
                    ("PARTY", "파티"),
                    ("OVERALL_NOTICE", "전체공지"),
                ],
                default="PIONEER",
                max_length=20,
                null=True,
                verbose_name="푸시 타입",
            ),
        ),
    ]
