# Generated by Django 3.1.5 on 2023-02-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_auto_20230213_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooiytiquestion',
            name='type',
            field=models.CharField(blank=True, choices=[('web', '웹'), ('app', '어플')], max_length=3, null=True, verbose_name='웹 | 앱'),
        ),
    ]
